### ISSUE TITLE
Refine AsyncAPI Bundling with Origin Tracing and Component Naming

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/bundler#141]
### Context
https://github.com/asyncapi/bundler/issues/97

### Summary:
Integrating the `optimizer` and `bundler` to enhance user experience requires a few modifications. These include removing redundant features, tracing the origins of references, and improving naming conventions within the bundled output.

#### 1) Simplify the Bundler by Removing `referenceIntoComponents`:
The `referenceIntoComponents` feature in the bundler seems to belong to the optimizer. Its removal should be straightforward:
- Identify the areas of code where the `referenceIntoComponents` flag is utilized.
- Ensure that the feature is decoupled without affecting other functionalities.
- Remove the feature and its flag entirely from the codebase.

#### 2) Traceability of `$ref` Origins Post-Bundling:
To maintain a clear lineage of `$ref` components post-bundling, it's necessary to include an `x-origin` property. This will annotate where the original `$ref` was located in the source files.

For example, transform this:
```yaml
...
  message:
    $ref: ./messages.yaml#/messages/UserSignedUp
...
```

Into this:
```yaml
...
  message:
    x-origin: ./messages.yaml#/messages/UserSignedUp
    payload:
      type: object
      properties:
        displayName:
          type: string
          description: Name of the user
...
```

#### 3) Introduction of a New Flag in the `optimizer`:
We propose adding a flag to the `optimizer` to centralize all components under the `components` section of an AsyncAPI document. The proposed flag is `moveAllComponents`. Alternative suggestions for the flag name are welcome for better intuitiveness.

#### 4) Intelligent Component Naming in the `optimizer`:
With the `x-origin` in place, the `optimizer` should leverage it to assign meaningful names to components, falling back to a standard naming convention (e.g., `message-1`) only when a better name isn't discernible from the context.

For instance, utilizing `UserSignedUp` derived from `x-origin` instead of a generic `message-1`.

**Comment by aeworxet** [comment]
@thake
Does point 2 presume carrying a satisfying amount of semantic meaning to serve your needs?

@derberg
Do you have any remarks concerning the task?

**Comment by thake** [comment]
@aeworxet, thanks for pinging me on this issue again!

The solution in point 2 (x-origin) does not cover my use case. I want refs to be bundled like they were defined in the common components of the AsyncAPI. By doing so, all tools that display AsyncAPIs would automatically display the name of the previously external component without additional work. By adding a new property `x-origin`, the same can't be achieved.

I've created a small example repo to demonstrate how it works with OpenAPI tooling: https://github.com/thake/openapi_bundling/tree/main

**Comment by aeworxet** [comment]
@thake Is this what you meant?

Transform this
```
...
  message:
    $ref: './messages.yaml#/messages/UserSignedUp'
...
```

Into this
```
...
  message:
    $ref: '#/components/messages/UserSignedUp'
...
```
```
...
  components:
    messages:
      UserSignedUp:
        x-origin: './messages.yaml#/messages/UserSignedUp'
        payload:
          type: object
          properties:
            displayName:
              type: string
              description: Name of the user
...
```

?

**Comment by aeworxet** [comment]
@KhudaDad414 Does @thake's request imply a rewriting of point 2 of the task and provide the direction in which point 4 should be solved?

**Comment by aeworxet** [comment]
I have taken a look at the way `Optimizer` [works currently](https://github.com/asyncapi/optimizer/blob/master/README.md) and it seems to be doing just what @thake wants.
So, in my opinion, `Bundler` should dereference all `$ref`s and create a raw merged AsyncAPI specification file, and `Optimizer` should move components to `components`, assigning them meaningful names and creating local `$ref`s in the place where they were taken from.
So the resulting YAML will be exactly what @thake needs, but in two steps, not in one.
And `x-origin`, well, it will just be there; as an FYI, it doesn't impact anything (except the quantity of traffic on a large number of connections to the server.)

Original
```yaml
...
  message:
    $ref: './messages.yaml#/messages/UserSignedUp'
...
```

After `Bundler`

```yaml
...
  message:
    x-origin: './messages.yaml#/messages/UserSignedUp'
    payload:
      type: object
      properties:
        displayName:
          type: string
          description: Name of the user
...
```

After `Optimizer`

```yaml
...
  message:
    $ref: '#/components/messages/UserSignedUp'
...
```
```yaml
...
  components:
    messages:
      UserSignedUp:
        x-origin: './messages.yaml#/messages/UserSignedUp'
        payload:
          type: object
          properties:
            displayName:
              type: string
              description: Name of the user
...
```

@thake Does this clarification still reflect what you meant?

**Comment by aeworxet** [comment]
About the new flag.

Given that there are already flags
`reuseComponents`
`removeComponents`
`moveToComponents`

I have two variants:
either
`moveAllToComponents`
(semantic naming)
or
`moveToComponentsAll`
(code-consistent naming.)

Which one would everyone choose?

**Comment by aeworxet** [comment]
In light of the release of the AsyncAPI Specification 3.0.0, should points 3 and 4 regarding `Optimizer` distinguish between v2 and v3 and work with them differently?

**Comment by KhudaDad414** [comment]
@aeworxet what about changing `moveToComponents` to `moveDuplicatesToComponents` and naming the new flag `moveAllToComponents`?



> In light of the release of the AsyncAPI Specification 3.0.0, should points 3 and 4 regarding `Optimizer` distinguish between v2 and v3 and work with them differently?

I don't see why would points 3 and 4 would treat v2 and v3 differently. 🤔

**Comment by aeworxet** [comment]
> I don't see why would points 3 and 4 would treat v2 and v3 differently. 🤔

Something from [here](https://www.asyncapi.com/docs/migration/migrating-to-v3)?
I'm simply making sure, because reasking dumb questions is cheaper than redoing cool code.

**Comment by aeworxet** [comment]
> I don't see why would points 3 and 4 would treat v2 and v3 differently.

I am concerned about
https://www.asyncapi.com/docs/migration/migrating-to-v3#operation-keywords
https://www.asyncapi.com/docs/migration/migrating-to-v3#messages-instead-of-message

@Souvikns already had to introduce changes to the `Bundler`'s codebase to support v3:
https://github.com/asyncapi/bundler/pull/140/files#diff-8c55dd6a23f93625d2343439d276efb2d1a9cfe097b5e124a80653995ca5b0e9R41
https://github.com/asyncapi/bundler/pull/140/files#diff-8c55dd6a23f93625d2343439d276efb2d1a9cfe097b5e124a80653995ca5b0e9R66

Might it be necessary to implement something similar for the `Optimizer`?

I would of course do a recursive search by mask so as not to depend on version changes, but still.

@jonaslagoni @derberg

**Comment by derberg** [comment]
yup, best if flow is `bundler` -> `optimizer` 
also, these are just repos and libraries. How we do it in CLI is up to us, and do it best for users. If it is really needed and makes lots of sense, in CLI we can have a command that allows you to use both libraries in one run

@aeworxet not sure why are you concerned about v2 vs v3
optimizer uses JS Parser and afaik it implements the API that at least in theory should abstract the structure of AsyncAPI document from you - so getting operations from v2 or v3 should actually work the same way

sorry if my answer do not address the question, I might not get it. I also forgot a lot from initial discussion and focused on other stuff, sorry

**Comment by derberg** [comment]
@aeworxet you added it to bounty, but tbh it is not `medium` imho, as take into account complexity of the topic - how long discussion is taking place. I'm not maintainer here, but imho this is really and `advanced` issue

**Comment by KhudaDad414** [comment]
@aeworxet your point is valid for the master branch. but https://github.com/asyncapi/optimizer/pull/193 is going to change the implementation so it uses parser-js. no issues there.

**Comment by aeworxet** [comment]
### Bounty Issue's service comment

Text labels: `bounty/2024-Q1`, `level/advanced`, `bounty/coding`
First assignment to third-party contributors: [2023-12-23 00:00:00 UTC+12:00](https://time.lol/#2023-12-23T00:00:00+12:00)
End Of Life: [2024-05-31 23:59:59 UTC-12:00](https://time.lol/#2024-05-31T23:59:59-12:00)

**Comment by aeworxet** [comment]
As an AsyncAPI Maintainer, I fall under the first category in the prioritization list, so I assign this issue to myself.

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Advanced        |2023-12-18                 |[2024-01-01](https://time.lol/#2024-01-01T00:00:00+12:00)              |**[2024-02-23](https://time.lol/#2024-02-23T23:59:59-12:00)**        |[2024-01-19](https://time.lol/#2024-01-19T23:59:59-12:00)         |[2024-02-09](https://time.lol/#2024-02-09T23:59:59-12:00)         |**[2024-02-23](https://time.lol/#2024-02-23T23:59:59-12:00)**    |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.

**Comment by aeworxet** [comment]
Is there a date when https://github.com/asyncapi/optimizer/pull/193 is expected to be merged? I would prefer to first add functionality to the `Optimizer` and only then delete it from the `Bundler`.

Would renaming `moveToComponents` -> `moveDuplicatesToComponents` be a breaking change (since `moveToComponents` is in the [`API.md`](https://github.com/asyncapi/optimizer/blob/master/API.md))?

**Comment by KhudaDad414** [comment]
> Is there a date when [asyncapi/optimizer#193](https://github.com/asyncapi/optimizer/pull/193) is expected to be merged? I would prefer to first add functionality to the `Optimizer` and only then delete it from the `Bundler`.

The work is done. it will be merged after I get a green light from @derberg 

> Would renaming `moveToComponents` -> `moveDuplicatesToComponents` be a breaking change (since `moveToComponents` is in the [`API.md`](https://github.com/asyncapi/optimizer/blob/master/API.md))?

yes, it is a breaking change. but since we haven't released v1 yet. I am not worried about breaking stuff. 🤷

**Comment by aeworxet** [comment]
@asyncapi/bounty_team

**Comment by aeworxet** [comment]
I need clarification on the task.
I can reach with 'standard' methods `$ref`s of the AsyncAPI Document provided as input, but not `$ref`s of `$ref`ed AsyncAPI Documents in it.
In case of input

**main.yaml**

```yaml
channels:
  commentLiked:
    address: comment/liked
    messages:
      commentLiked:
        $ref: '../common/messages.yaml#/commentLiked'
```

**../common/messages.yaml**

```yaml
commentLiked:
  description: Message that is being sent when a comment has been liked by someone.
  payload: 
    $ref: './schemas.yaml#/commentLikedPayload'
```

**./schemas.yaml**

```yaml
commentLikedPayload: 
  type: object
  title: commentLikedPayload
  additionalProperties: false
  properties:
    commentId: 
      allOf: 
        - $ref: '#/commentId'
        - description: Id of the comment that was liked
```

the result is

```yaml
channels:
  commentLiked:
    address: comment/liked
    messages:
      commentLiked:
        x-origin: ../common/messages.yaml#/commentLiked
        description: Message that is being sent when a comment has been liked by someone.
        payload:
          # here is supposed to be the 'x-origin: ./schemas.yaml#/commentLikedPayload'
          type: object
          title: commentLikedPayload
          additionalProperties: false
          properties:
            commentId:
              allOf:
                - type: string
                - description: Id of the comment that was liked
```

From one hand, the task is about adding `x-origin` to COMPONENTS. It's being added to components, so I could call it a day.
But what's the sense of adding `x-origin` properties at all, if they are not added through ALL AsyncAPI Document?

And here comes the tricky part.

The easiest solution would be to alter copies of original AsyncAPI Documents on the filesystem.
I can make copies of `$ref`ed AsyncAPI Documents on the filesystem (even if I request one from the network, I can still save it, load from the filesystem, iterate through it, make modifications, and save again.)
But then `Bundler` starts to be engaged in a too much filesystem activity.

Or I can find paths to all `$ref`ed AsyncAPI Documents load them into memory, iterate through them, make modifications and merge copies of them into the main AsyncAPI Document.
But more code introduces more bugs (talking about temptation of some engine to save reference to the original object even in case of deep cloning, due to their own bug.)

So, what should be the golden mean here?
