### ISSUE TITLE
[FEATURE] `Bundler` to have more flexible and configurable behavior for circular refs

### ISSUE THREAD

**Issue by 412b** [asyncapi/bundler#201]
### Why do we need this improvement?

Despite being called `bundler` it does dereferencing, which blocks the use of it for schemas with circular references.
`json-schema-ref-parser` used under the hood has mutiple options for handling circular refs and even a dedicated `bundle` function for actually bundeling.
moreover, further down the `asyncapi` stack circular refs are not a problem, e.g. `modelina` can handle schemas with circular refs and generate code for those.

### How will this change help?

it will unblock the use of `bundler` for cases with circular refs and make the tool more close functions-wise to its name.

### How could it be implemented/designed?

default behavior can remain the same, and additional option may enable a behavior of really just bundling
also mixed dereference via [dereference.circular](https://apidevtools.com/json-schema-ref-parser/docs/options.html)=ignore can be achieved.

from the first look at the code base it can be a single additional cli arg (e.g. named `strategy`) describing the desired behaviours:
- dereference all (default and current behavior)
- dereference circular
- dereference all except circular
- bundle (via using `json-schema-ref-parser`'s `bundle`)

no real complexity of the change, but quite some additional value for the tool.

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [x] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

**Comment by aeworxet** [comment]
@412b 
Could you please provide examples of the original schema(s) and the expected results for each case?

**Comment by 412b** [comment]
> [@412b](https://github.com/412b) Could you please provide examples of the original schema(s) and the expected results for each case?

sure, it's a more of expected behavior here, 'cause I don't have time to test it in real-life, but conceptually it should work as follows:
**Input**
asyncapi.yml
```yaml
asyncapi: 3.0.0
info:
  title: Test model
  version: 1.0.0
components:
  messages:
    btree:
      title: BTree
      payload:
        $ref: "./btree.yaml"
```
btree.yaml
```yaml
$schema: "https://json-schema.org/draft-07/schema#"
title: BTree
type: object
properties:
  root:
    $ref: "./node.yaml"
```
node.yaml
```yaml
$schema: "https://json-schema.org/draft-07/schema#"
title: Node
type: object
properties:
  left:
    $ref: "#"
  right:
    $ref: "#"
```

**Result**
1. dereference all
`ReferenceError: Circular $ref pointer found at`

2. dereference circular
here I'm not 100% sure, how exactly the schema will be dereferenced, because docs don't give enough of examples

3. dereference all except circular
```yaml
asyncapi: 3.0.0
info:
  title: Test model
  version: 1.0.0
components:
  messages:
    btree:
      title: BTree
      payload:
        $schema: "https://json-schema.org/draft-07/schema#"
        title: BTree
        type: object
        properties:
          root:
            $schema: "https://json-schema.org/draft-07/schema#"
            title: Node
            type: object
            properties:
              left:
                $ref: "#/components/messages/btree/payload/properties/root"
              right:
                $ref: "#/components/messages/btree/payload/properties/root"
```

4. bundle
here I'm again not 100% sure of the output due too lack of docs, but should be pretty close to pt. 3
```yaml
asyncapi: 3.0.0
info:
  title: Test model
  version: 1.0.0
components:
  messages:
    btree:
      title: BTree
      payload:
        $schema: "https://json-schema.org/draft-07/schema#"
        title: BTree
        type: object
        properties:
          root:
            $schema: "https://json-schema.org/draft-07/schema#"
            title: Node
            type: object
            properties:
              left:
                $ref: "#/components/messages/btree/payload/properties/root"
              right:
                $ref: "#/components/messages/btree/payload/properties/root"
```


examples are lacking precision of course, but in worst case I see only number of options being reduced in the PR, while writing the tests and checking th real-life behavior.

**Comment by 412b** [comment]
thus it may even end up with only 2 options:
- all
- non-circular

**Comment by aeworxet** [comment]
@412b 
### Comments on your requests:

- dereference all (default and current behavior)
  - No changes are needed.

- bundle (via using json-schema-ref-parser's bundle)
  - `Bundler` uses `onDereference` function to save the properties `x-origin`. Therefore, to avoid introducing complex conditions - such as '_option `bundle` disables the possibility to save the `x-origin` property, so you can use only either one or the other_' - `bundle` functionality can be implemented only after the `onBundle` callback, which has similar functionality to `onDereference` [is implemented](https://github.com/APIDevTools/json-schema-ref-parser/issues/346) in `@apidevtools/json-schema-ref-parser` (in development [since 2024-04-27](https://github.com/APIDevTools/json-schema-ref-parser/issues/346#issuecomment-2080266029)).

- dereference all except circular
  - Functionality [can be achieved](https://apidevtools.com/json-schema-ref-parser/docs/options.html) by setting `dereference.circular` to `ignore`. Should a separate flag be introduced?

- dereference circular
  - There is no immediate answer on how to achieve this in this particular case; the topic needs to be researched.

**Comment by 412b** [comment]
@aeworxet 

real-life renderings via `dereference`:
- `circular = true`. breaks the toolchain, can be discarded completely due to anchors.
```yaml
asyncapi: 3.0.0
info:
  title: Test model
  version: 1.0.0
components:
  messages:
    btree:
      title: BTree
      payload:
        $schema: https://json-schema.org/draft-07/schema#
        title: BTree
        type: object
        properties:
          root: &ref_0
            $schema: https://json-schema.org/draft-07/schema#
            title: Node
            type: object
            properties:
              left: *ref_0
              right: *ref_0
            x-origin: ./node.yml
        x-origin: ./btree.yml
```

- `circular = 'ignore'`. does nothing for example provided, can be discarded.
```yaml
    asyncapi: 3.0.0
    info:
      title: Test model
      version: 1.0.0
    components:
      messages:
        btree:
          title: BTree
          payload:
            $ref: ./btree.yml
```

more useful results we're obtained by using `bundle` before `dereference`.
- `circular = 'ignore'`. perfect resolution, best option so far.
```yaml
asyncapi: 3.0.0
info:
  title: Test model
  version: 1.0.0
components:
  messages:
    btree:
      title: BTree
      payload:
        $schema: https://json-schema.org/draft-07/schema#
        title: BTree
        type: object
        properties:
          root:
            $schema: https://json-schema.org/draft-07/schema#
            title: Node
            type: object
            properties:
              left:
                $ref: '#/components/messages/btree/payload/properties/root'
              right:
                $ref: '#/components/messages/btree/payload/properties/root'
```
there are only 2 side-effects of using `bundle`:
1. no `x-origin`, because nobody implemented the callback feature for `bundle` in `json-schema-ref-parser`
2. one test showed, that `$ref` changed, needs a bit of check, if the result is still valid.

the research is 90% of the PR, that I am ready to submit (does the feature need approval still?) and lead it to the finish line.
