### ISSUE TITLE
Support `referenceIntoComponents` for other components than `message`

### ISSUE THREAD

**Issue by thake** [asyncapi/bundler#97]
#### Reason/Context
Currently, the `referenceIntoComponents` option only seems to work for `message` components. However, it can also be useful for all other component types (see https://www.asyncapi.com/docs/reference/specification/v2.5.0#componentsObject).

#### Description
Changes:
- Extend https://github.com/asyncapi/bundler/blob/master/src/parser.ts so that it detects all kinds of references.

Although the bundled spec will change, I would not consider this feature as a breaking change. Implementing this feature would only mean the correct implementation of the current documentation of the `referenceIntoComponents` flag: 
> Pass `true` to resolve external references to components.

**Comment by derberg** [comment]
I think if maybe we should plug in https://github.com/asyncapi/optimizer/ or not even plug in but simply describe how both should be used 🤔 

cc @KhudaDad414 @Souvikns

**Comment by Souvikns** [comment]
While building `reference-into-components` feature I thought I could use optimiser for resolving references but that was not possible, what we can do is optimize the document after all the referencing is done, will open a proposal for this soon.

**Comment by derberg** [comment]
@Souvikns do you remember the reason? it would be good to have one mechanism for things like this. But of course only if it makes sense and will help and not complicated life

**Comment by aeworxet** [comment]
While trying to find out what would be better architecturally:

- searching for objects that can be moved to `components`, in predefined places (like `crawlChannelPropertiesForRefs()`
https://github.com/asyncapi/bundler/blob/42a2b189e8303b57f8fcbc14c721637838ae504f/src/parser.ts#L33..L35
that searches for a known in advance object in a predefined place)

- or going from list of objects that CAN exist in `Components Object`
```
schemas
servers
channels
operations       <-- will be added in specification 3.0.0
messages
securitySchemes
serverVariables
parameters
correlationIds
externalDocs     <-- will be added in specification 3.0.0
tags             <-- will be added in specification 3.0.0
operationTraits
messageTraits
serverBindings
channelBindings
operationBindings
messageBindings
```
and search, say, for `message` through all schema (iterate through all properties of the schema object), and if it finds a `message` (with a `$ref` which is an external $ref), then this `$ref` is dereferenced, and full dereferenced message object is moved to `components: { messages: {} }`,

I found that there exists one big pro in the second approach, which will make the solution more generic (@magicmatatjahu): if objects move around the schema as specification changes with time, nothing would change for Bundler who in search of suitable objects was iterating through all of the schema object from the start.

And this led me to using @derberg's and @Souvikns's idea of utilizing Optimizer as much as possible.

'As much as possible' I see as adding to Optimizer the ability to dereference external references **before** starting the optimization of a given schema, and then Bundler will only merge schemas Optimizer will give out to it (because by logic, Optimizer is meant to OPTIMIZE ONE given schema, and Bundler is meant to BUNDLE SEVERAL schemas into one).
@KhudaDad414

@jonaslagoni do you have additions or comments?

**Comment by Souvikns** [comment]
> @Souvikns do you remember the reason? it would be good to have one mechanism for things like this. But of course only if it makes sense and will help and not complicated life

optimizer currently does not resolve external references, and only works with internal references, so to build the `reference-into-components` we could not use optimizer. But we can use optimizer after the bundling step when all the external references are resolved and files are merged, then optimizer can optmize the document since there is only internal references to work with. (currently only true for messages)

> 'As much as possible' I see as adding to Optimizer the ability to dereference external references before starting the optimization of a given schema, and then Bundler will only merge schemas Optimizer will give out to it (because by logic, Optimizer is meant to OPTIMIZE ONE given schema, and Bundler is meant to BUNDLE SEVERAL schemas into one).
@KhudaDad414

Are you suggesting that we move the external reference logic to optimizer?

**Comment by aeworxet** [comment]
> Are you suggesting that we move the external reference logic to optimizer?

Not move but copy. Extend Optimizer's functionality. And Bundler will use it after extension.

I can even take such a task.

The question is whether there is a need in such functionality, and if it doesn't go against Optimizer's concept (it might be intended for local use only.)
For now AFAIK external references dereference `parser-js` and `bundler`. Those are only the ones that I know. So such functionality might become available in all AsyncAPI Initiative tools by default. (it might be even time already to create a library that holds all reusable code 😆)

**Comment by KhudaDad414** [comment]
TBH, I don't think moving components to the `components` section is ideal unless we gain some specific benefits. why? since it adds complexity and makes the specification file harder to read for humans.
In the optimizer, we accept this complexity since it provides reusability by only moving components to the components section if there is more than one copy of the same component.

If I only have one copy of a message why would I want to move it to the components section? I want to have it where it belongs.

I think we should let each of these tools do its thing. let the `bundler` bundle the specification into one file and let the optimizer check the output of the bundler and move components to the components section if there are reusability benefits.

**Comment by derberg** [comment]
The thing is that it is a recommendation to put as much as possible in `components`. At least I always recommend this way.

Reading huge YAML is hard, but when things are moved into `components` it is easier. As long as you read YAML in editor that supports `$ref` that allows you to click it and go into a given reffed component. 

But of course moving something to components, if there is just one ref that will use it, do not make much sense either 😄 
---

anyway 😄 

`bundler` -> `optimizer` user flow makes much more sense to me really. 

At the library level, we just explain what people should do, and we make sure that these libraries are not heavy.
At CLI or Studio level, we can abstract it in a way that you can still bundle or optimize separately but we also enable that when you bundle, you can also pass a flag like `--moveToComponents` (just quick idea, to be discussed once work on CLI happens) that will trigger optimization after bundling (same can be done in Studio).

**Comment by magicmatatjahu** [comment]
Yes, the bundler is supposed to do one thing and the optimizer something else, combining it should only be done in integrations like CLI or Studio. As for the approach, as you wrote yourself, the generic approach is better. I'm just wondering whether we should use the API from the parser to bundle external references more easily, or rather write all the logic from scratch. Of course, the parser (for now) does not provide all the data needed for proper bundling (e.g. the original reference of the de-referenced object), but if it did, it would make the work on the bundler much easier.

Currently, you can create this generic function and try to bundle only the message as the bundler currently works, and in other PRs we can add other components to bundle - to do it iteratively.

**Comment by magicmatatjahu** [comment]
On the other hand, bundler could work as a combination of parser + optimizer, because at the end, the bundled spec should look identical if you use a parser and then an optimizer 😄

**Comment by thake** [comment]
I just want to highlight a potential problem if moving to components is done in a separate step after bundling:

The $ref usually also carries a semantical meaning to understand easier what it is (example "$ref : financial-system.yaml#/components/schemas/bankAccountIdentifier"). If the bundling just resolves this ref inline, the semantical meaning of the $ref pointer gets lost and cannot be recovered in later steps. The optimizer would need to invent an artificial component name for the "bankAccountIdentifier" when moving it to the components section.

Because of this, I think moving to the components section needs to be done in the bundler itself.

**Comment by aeworxet** [comment]
Maybe Bundler, besides everything, should also make a list of original `$ref`s via `Specification Extensions`?

Something like
```
"x-parser-original-refs": {
  "./financial-system.yaml#/components/schemas/bankAccountIdentifier": "#/components/schemas/bankAccountIdentifier"
}
```
or `"x-bundler-original-refs"` or simply `"x-original-refs"`?
Just to keep traceability of where each resolved ref came from.

It could be a separate boolean option, like `saveOriginalRefs: true`.

**Comment by aeworxet** [comment]
## Conversion of this high-level discussion into a technical task.


Bundler does only one job: it bundles several specifications into one file (dereferencing external `$ref`s), optionally aggregating all AsyncAPI Specification-legal components in the `components` object. Anything more than this is the concern of other tools.

Bundler accepts three options:
```
referenceIntoComponentsAll: true | false
referenceIntoComponentsOptimize: true | false
saveOriginsOfRefs: true | false
```


#### `referenceIntoComponentsAll` || `referenceIntoComponentsOptimize`
ONE, and ONLY ONE, of options `referenceIntoComponentsAll` and `referenceIntoComponentsOptimize` can equal `true`.
- If both options equal `true`, `referenceIntoComponentsAll` takes higher priority, and the `referenceIntoComponentsOptimize` is forced to equal `false`.
- If both options equal `false`, Bundler only bundles and dereferences external `$ref`s, without searching for AsyncAPI Specification-legal components and performing any optimization on the resulting specification.
- If none of two options is specified, they are both considered `false`.
- If one of two options is not specified, the non-specified option is considered `false`.


#### `referenceIntoComponentsAll` **(optional)** (`referenceIntoComponents` is also queried, to provide backward compatibility with existing `referenceIntoComponents`, issuing a warning of future deprecation)
If equals `true`, 'Bundler only' workflow is used.
ALL, and EVERY, AsyncAPI Specification-legal component is moved into `components` object, regardless of optimization considerations.
Bundler's internal generic mechanism to find every AsyncAPI Specification-legal component throughout all of the schema object is used in this case.


#### `referenceIntoComponentsOptimize` **(optional)**
If equals `true`, 'Bundler -> Optimizer' workflow is used.
Bundler bundles several specifications into one file (dereferencing external `$ref`s) and lets the Optimizer check the output.
Optimizer moves components to the `components` object if there is more than one copy of the same component (if there are reusability benefits).


#### `saveOriginsOfRefs` **(optional)**
If equals `true`, Bundler creates list of origins of external `$ref`s via `Specification Extensions`, in form
```
{
  "x-origins-of-refs": {
    "#/components/schemas/bankAccountIdentifier": "./financial-system.yaml#/components/schemas/bankAccountIdentifier"
  }
}
```
to keep traceability of where each resolved external `$ref` came from.
#
Please react with `like`/`dislike`/`seen` or add comments.

**Comment by KhudaDad414** [comment]
> Of course, the parser (for now) does not provide all the data needed for proper bundling (e.g. the original reference of the de-referenced object), but if it did, it would make the work on the bundler much easier.

This. I mean I am ready to sign off my firstborn child for this feature. 😆  This would make the logic of the optimizer much simpler. do we have an issue for this? @magicmatatjahu 

@thake has a point here https://github.com/asyncapi/bundler/issues/97#issuecomment-1330501758 but if the `parser` provides that piece of information, the optimizer can do it as well. 

I don't have any strong opinion about @aeworxet's proposal. but if we save the origin of refs, it should be the same in `parser` so other tools can consume it easily.

**Comment by aeworxet** [comment]
And this again raises the question about the library which would contain all reusable code, used by all tools, through all of the AsyncAPI Initiative. 😀
Could be a library, like `@asyncapi/library-js`/`@asyncapi/library-ts`/`@asyncapi/library-go` etc.
Could be a collection of code snippets for different languages (though being a 'collection of snippets' would lower its 'official' status).
Could be a collection of 'AsyncAPI best practices'.
Could be a collection of pseudocode snippets (to make it language-agnostic) reflecting AsyncAPI Initiative's best practices.

Could be anything - the idea here is about having a centralized store of reusable code, like 'standard library' in programming languages or frameworks.

Also, it could be a separate exported function in parser, of course.

**Comment by aeworxet** [comment]
Then I will simply extend the functionality of the Bundler's option `referenceIntoComponents` to 
```
ALL, and EVERY, AsyncAPI Specification-legal component is moved into `components` object,
regardless of optimization considerations.
Bundler's internal generic mechanism to find every AsyncAPI Specification-legal component
throughout all of the schema object is used in this case.
```
as @thake requested and that's it.

Optimization of the resulting specification after Bundler, will be a separate process, handled by Optimizer at CI level.

Creating the list of origins of external `$ref`s via `Specification Extensions`, to keep traceability of where each resolved external `$ref` came from, will be the functionality of `parser-js`, and Bundler will import this function during bundling, in case `saveOriginsOfRefs: true` is specified in its options (say, dynamic import).

How about this?

**Comment by magicmatatjahu** [comment]
> Then I will simply extend the functionality of the Bundler's option referenceIntoComponents to

👌🏼 

> Optimization of the resulting specification after Bundler, will be a separate process, handled by Optimizer at CI level.

Yeah but without `referenceIntoComponentsOptimize` parameter in thebundler options. That option should be added in the integrations :)

> Creating the list of origins of external $refs via Specification Extensions, to keep traceability of where each resolved external $ref came from, will be the functionality of parser-js, and Bundler will import this function during bundling, in case saveOriginsOfRefs: true is specified in its options (say, dynamic import).

Yeah, it could be :)

Thanks @aeworxet for your awesome work! Let's wait for comments from another people :)

**Comment by derberg** [comment]
Lemme summarize as I'm a bit lost

- no need for `referenceIntoComponentsOptimize` as this should be just integrated in CLI or other tools, use bundler and optimizer separately
- I agree we do not need `referenceIntoComponentsAll`. Especially that bundler did not reach major release yet. Breaking changes are expected, and even if we do not like them, then let's just release 1.0
- I get that parser could and actually is the only place where we could implement functionality to preserve $ref info (actually I think we need it with 3.0 because of inification to use `$ref` everywhere where needed)

What I don't get, why we need `referenceIntoComponents` here instead of having `optimizer` handle it 😄 

- bundler should bundle references to locations where they point from. I actually think current `referenceIntoComponents` is a bit beyond bundler scope
- I know `optimizer` is not moving to components stuff that showed up only once, but we can have it behind an option, right? in the end it is optimization for some folks, some schemas might be super large and you want them in `components`. This is a perfect real-world example where the schema is huge, one in the entire file but you still want to move it to `components` because it is hard to read other info from the file -> https://docs.confluent.io/cloud/current/stream-governance/async-api.html#components-section

---

Look at this example

```yml
asyncapi: '2.5.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        payload:
          $ref: 'https://raw.githubusercontent.com/asyncapi/studio/354e1cfa51b2d79d855d5aeb74c431a1b5f04cfb/src/examples/simple.yml#/components/messages/UserSignedUp/payload'
```

bundler should turn it into 
```yml
asyncapi: '2.5.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        payload:
          type: object
          properties:
            displayName:
              type: string
              description: Name of the user
            email:
              type: string
              format: email
              description: Email of the user
```

optimizer into
```yml
asyncapi: '2.5.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        payload:
          $ref: '#/components/schemas/UserSignedUp'
components:
  schemas:
    UserSignedUp:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user
```

And yes, I know it won't work as described above as optimizer cannot guess `UserSignedUp` schema name.
Even if we preserve $ref (https://raw.githubusercontent.com/asyncapi/studio/354e1cfa51b2d79d855d5aeb74c431a1b5f04cfb/src/examples/simple.yml#/components/messages/UserSignedUp/payload) we also are not sure we can use it for getting the schema name. The solution is to rely on `uid` helpers that extract it from different locations, like `name` in case of message or `$id` in case of schemas.

@KhudaDad414 what you do in optimizer? use helper functions from parser models or just automatically generate these names of components?

**Comment by KhudaDad414** [comment]
@derberg optimizer generates names for schemas and it uses the `name` in case of messages. I totally remember looking into it a year ago and seeing there was some room for improvements in naming. there was a useful field that was coming from the parser(I don't exactly remember what 🤦). I will look into it.

**Comment by aeworxet** [comment]
Is there a final decision, whether Bundler's `referenceIntoComponents` should be extended or removed completely?

**Comment by Souvikns** [comment]
I agree that `referenceIntoComponents` should be something handled by the optimizer, in fact the example @derberg is using, I was actually thinking of the same thing, that bundler would resolve the references and then optimizer could localize them further, I even had a talk with @KhudaDad414 about this, where I learned that this is not possible for the optimizer. If there would two copies of the payload in two different places then the optimizer could help. 

@KhudaDad414 if you are up for it, I would love to move this feature, to optimizer and then update bundler to use optimizer to `referenceIntoComponents`

**Comment by derberg** [comment]
just keep in mind @Souvikns, that once we get it handled by optimizer, there is no need for `referenceIntoComponents` anymore. On library level we would just advice people to use both, bundler and then optimizer, and on CLI level we can do `referenceIntoComponents` that basically calls optimizer, so people do not have to do `asyncapi bundle & asyncapi optimize`

**Comment by magicmatatjahu** [comment]
@derberg 

> - bundler should bundle references to locations where they point from. I actually think current referenceIntoComponents is a bit beyond bundler scope
> - I know optimizer is not moving to components stuff that showed up only once, but we can have it behind an option, right? in the end it is optimization for some folks, some schemas might be super large and you want them in components. This is a perfect real-world example where the schema is huge, one in the entire file but you still want to move it to components because it is hard to read other info from the file

I think that the bundler itself should also transfer some things to the components - that's how bundlers should work - the optimizer is an add-on that can simplify the specifications, but it should not take whole "care" of the reference thing in bundling phase (or after it) - but extend it. To be clear, the appearance of several references to the same file should be bundled like the `json-schema-ref-parser` does.

**Comment by magicmatatjahu** [comment]
By transfer I mean that references defined multiple times go to some place with definitions/components - https://github.com/APIDevTools/json-schema-ref-parser works in this way.

**Comment by derberg** [comment]
just to make sure I get it in case of ref parser bundler:
- you have a file with two references pointing to exactly the same URL
- bundler will move referenced item to `definitions` only once and modifies two references to local reference pointing to `definitions`

and what you mean is that the same should be for this bundler? that whenever there is for example `payload` reference to outside, the same `payload` reference in 2 different messages, after bundling, should be modified to point to new local reference to `components.schema` (schema moved from external reference). And this should be default?

Isn't it actually how bundler works like at the moment?

**Comment by magicmatatjahu** [comment]
Yes, but only related to the external refs.

**Comment by derberg** [comment]
So it is good right. Bundler should not mess with internal references.

**Comment by derberg** [comment]
@magicmatatjahu yo, can you have a look at my last comment. It would be good to reach some consensus here

**Comment by magicmatatjahu** [comment]
> and what you mean is that the same should be for this bundler? that whenever there is for example payload reference to outside, the same payload reference in 2 different messages, after bundling, should be modified to point to new local reference to components.schema (schema moved from external reference). And this should be default?
>
> Isn't it actually how bundler works like at the moment?

It works like you described but it should work for every type of refs, e.g. not only for messages but for schemas, parameters, server variables etc.

So yeah, bundler should check if external ref is used at least two times and move that ref (with resolved/value) to the `components.[type of object]`) and that's it. Someone can say that behaviour (I mean referencing two this same references to components) is reserved for optimizer, but as I wrote, optimizer is add-on to show that something should be optimized, like removing unused components etc.

**Comment by derberg** [comment]
> optimizer is add-on to show that something should be optimized

it shows and can also do the optimization for you, and one of these is moving stuff that occurs more than once to components.

Input:

```yaml
asyncapi: '2.5.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup1:
    subscribe:
      message:
        payload:
          $ref: 'https://raw.githubusercontent.com/asyncapi/studio/354e1cfa51b2d79d855d5aeb74c431a1b5f04cfb/src/examples/simple.yml#/components/messages/UserSignedUp/payload'
  user/signedup2:
    publish:
      message:
        payload:
          $ref: 'https://raw.githubusercontent.com/asyncapi/studio/354e1cfa51b2d79d855d5aeb74c431a1b5f04cfb/src/examples/simple.yml#/components/messages/UserSignedUp/payload'
```

should be bundled in dummy way as:
```yaml
asyncapi: '2.5.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup1:
    subscribe:
      message:
        payload:
           type: object
           properties:
                displayName:
                    type: string
                    description: Name of the user
                email:
                    type: string
                    format: email
                    description: Email of the user
  user/signedup2:
    publish:
      message:
        payload:
           type: object
           properties:
                displayName:
                    type: string
                    description: Name of the user
                email:
                    type: string
                    format: email
                    description: Email of the user
```

Bundler should not recognize that there are duplicates and move stuff to components, this logic belongs to `optimizer`

**Comment by magicmatatjahu** [comment]
@derberg Nope, bundler should also save this same references.

**Comment by derberg** [comment]
> bundler should also save this same references (only external ones)

sorry but I do not understand what you mean 😞

**Comment by magicmatatjahu** [comment]
Ok, I'll explain again how it should work. I will show how bundling works in https://github.com/APIDevTools/json-schema-ref-parser library, based on JSON Schema examples, so that everyone can test it themselves.

Having schemas like:

```yaml
# my-schema.yaml
type: object
properties:
  external:
    $ref: './definition.yaml#/User/properties/name'
  externalMulti1:
    $ref: './definition.yaml'
  externalMulti2:
    $ref: './definition.yaml'

# definition.yaml
User:
  type: object
  required: [name]
  properties:
    name:
      type: string
  examples:
    - name: "Homer"
```

and code

```js
import $RefParser from '@apidevtools/json-schema-ref-parser';

async function main() {
  const schema = await $RefParser.bundle("my-schema.yaml");
  console.log(schema);
}
main();
```

we have output:

```yaml
{
  type: 'object',
  properties: {
    external: { '$ref': '#/properties/externalMulti1/User/properties/name' },
    externalMulti1: { User: [Object] },
    externalMulti2: { '$ref': '#/properties/externalMulti1' }
  }
}
```

so as we can see, `@apidevtools/json-schema-ref-parser` first resolves refs and tries to "optimize" them as much as it can. `externalMulti1` field has full external object and the next one fields has subset of object or whole object, but "saved" as internal references (references in this same file/document). In our bundling we don't need such a optimization, because that should be handled by `optimizer` library, however... we should "optimize" external references saving them in the `components` object if this same external reference is used at least two times in document (not subset, this same reference, this same value in `$ref` field) - to decrease size of document, so example from @derberg, should be bundled to this:

```yaml
asyncapi: 2.6.0
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup1:
    subscribe:
      message:
        payload:
          $ref: '#/components/schemas/UserSignedUpPayload'
  user/signedup2:
    publish:
      message:
        payload:
          $ref: '#/components/schemas/UserSignedUpPayload'
components:
  schemas:
    UserSignedUpPayload: # the id of external reference can be generated or can use subset of ref path
      type: object
         properties:
            displayName:
              type: string
              description: Name of the user
            email:
              type: string
              format: email
              description: Email of the user
``` 

In other example, if someone use only one time given external ref, it should look like (external ref should be written to document inline in given place, where ref is defined):

```yaml
asyncapi: '2.5.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup1:
    subscribe:
      message:
        payload:
           type: object
           properties:
                displayName:
                    type: string
                    description: Name of the user
                email:
                    type: string
                    format: email
                    description: Email of the user
```

How I would do it and so I recommend that it should work that way. We can always add options like `optimizeExternalRefs` which would "shorten" the document by moving such repeated external references more than 1 time to components. if someone would define this option as `false`, the bundler would work as @derberg described.

Now I am not sure if our bundler works identically as I described for messages objects. If yes then ok, and we should extend this logic to other object types present in AsyncAPI document. Is my idea already understood?
